#include "classes.h"
#include "base.h"
#include "MaxValues/stdafx.h"
#include "MinValues/stdafx.h"
#include "Bits/stdafx.h"
#include "Strings/stdafx.h"
#include "Memory/stdafx.h"
#include "Conversion/stdafx.h"
#include "BigObject.h"
#include "Variable.h"

#include "Math/stdafx.h"
#include "Network/stdafx.h"